In [8]:
import pandas as pd

df = pd.read_csv("data/DATA_2022년_국민여행조사_원자료.csv", encoding='cp949', low_memory=False)

# 필요한 칼럼만 추출
df = df[['D_TRA1_CASE', 'D_TRA1_COST', 'D_TRA1_ONE_COST', 'A9C', 'A9D']]

# 새로운 CSV 파일로 저장
df.to_csv("data/new_file.csv", index=False, encoding='cp949')

# 저장한 CSV 파일 읽기
df2 = pd.read_csv("data/new_file.csv", encoding='cp949')

df2 = df2.dropna()
df2

,D_TRA1_CASE,D_TRA1_COST,D_TRA1_ONE_COST,A9C,A9D
1,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",800000.0,160000.0,200000.0,180000.0
3,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",1000000.0,1000000.0,170000.0,280000.0
4,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",399999.0,133333.0,120000.0,21999.0
6,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",600003.0,200001.0,140001.0,170001.0
7,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",100000.0,50000.0,0.0,52000.0
...,...,...,...,...,...
52024,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",150000.0,150000.0,20000.0,40000.0
52029,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",200000.0,200000.0,0.0,70000.0
52033,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",20000.0,20000.0,0.0,0.0
52034,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",40000.0,40000.0,0.0,20000.0
52039,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",40000.0,40000.0,0.0,20000.0

In [10]:
df3 = pd.read_csv("data/DATA_2022년_국민여행조사_원자료.csv", encoding='cp949', low_memory=False)
df3

,ID,SA1_1,SA1_2,SA1_3,SA1_4,SA1_5,MON_EXP_1,MON_EXP_2,MON_EXP_3,MON_EXP_4,...,국내_여행방문지_기타당일1,국내_여행방문지_기타당일2,국내_여행방문지_기타당일3,국내_여행방문지_기타당일4,국내_여행방문지_기타당일5,국내_여행방문지_기타당일6,국내_여행방문지_기타당일7,국내_여행방문지_기타당일8,국내_여행방문지_기타당일9,국내_여행방문지_기타당일10
0,11010550211_277566,0.0,0.0,0.0,0.0,0.0,아니오,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11010550211_277569,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11010550211_277571,0.0,0.0,0.0,0.0,0.0,아니오,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11010550211_277572,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11010550211_277588,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52036,3902059083A_580655,0.0,0.0,0.0,0.0,0.0,아니오,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52037,3902059083A_580912,0.0,0.0,0.0,0.0,0.0,아니오,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52038,3902059083A_580913,0.0,0.0,0.0,0.0,0.0,아니오,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52039,3902059083A_580914,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52040,3902059083A_580918,0.0,0.0,0.0,0.0,0.0,아니오,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN